<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <Authors>Cloris</Authors>
    <RootNamespace>$(Authors).$(MSBuildProjectName)</RootNamespace>
    <VssdkCompatibleExtension>true</VssdkCompatibleExtension>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="icon.png" />
  </ItemGroup>
  <ItemGroup>
	  <PackageReference Include="Microsoft.VisualStudio.Extensibility.Sdk" Version="17.14.40608" PrivateAssets="all" />
	  <PackageReference Include="Microsoft.VisualStudio.Extensibility.Build" Version="17.14.40608" PrivateAssets="all" />
     <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.269" PrivateAssets="all" />
	  <PackageReference Include="Microsoft.VisualStudio.SDK" Version="17.14.40265" ExcludeAssets="runtime" />
  </ItemGroup>

  <ItemGroup>
	  <Reference Include="PresentationCore" />
	  <Reference Include="PresentationFramework" />
	  <Reference Include="System.Xaml" />
  </ItemGroup>

</Project>
